# Generated by Django 5.1.4 on 2025-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_roomcheck_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheck_tbl',
            name='in_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomcheck_tbl',
            name='out_date',
            field=models.CharField(max_length=100),
        ),
    ]
