# Generated by Django 5.1.4 on 2025-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_roomcheck_tbl_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheck_tbl',
            name='in_date',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomcheck_tbl',
            name='out_date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
