# Generated by Django 5.1.4 on 2025-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_roomcheck_tbl_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='roomcheck_tbl',
        ),
    ]
