# Generated by Django 5.1.4 on 2025-03-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_roombooking_tbl_delete_roomcheck_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking_tbl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.register_tbl'),
            preserve_default=False,
        ),
    ]
