# Generated by Django 5.1.4 on 2025-03-19 12:08

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_roombooking_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking_tbl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='my_app.register_tbl'),
        ),
    ]
