# Generated by Django 5.1.4 on 2025-03-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_roombooking_tbl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking_tbl',
            name='user',
        ),
    ]
