# Generated by Django 4.2 on 2025-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
