# Generated by Django 4.2 on 2025-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_reservation_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_A_Comment_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nmae', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.CharField(max_length=100)),
                ('Messages', models.CharField(max_length=100)),
            ],
        ),
    ]
