# Generated by Django 4.2 on 2025-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_leave_a_comment_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_a_comment_tbl',
            name='Messages',
            field=models.TextField(max_length=100),
        ),
    ]
