# Generated by Django 4.2 on 2025-03-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_leave_a_comment_tbl_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_a_comment_tbl',
            old_name='Email',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='leave_a_comment_tbl',
            old_name='Nmae',
            new_name='Name',
        ),
    ]
