# Generated by Django 4.2 on 2025-03-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_contact_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking_tbl',
            name='user',
        ),
    ]
